#!/bin/bash

az_metadata_env() {
  local tmp=
  tmp="$(mktemp --tmpdir az_metadata-XXXXX.env)"
  (
  set -eo pipefail
  curl -fsSL --connect-timeout 1 -H Metadata:true 'http://169.254.169.254/metadata/instance?api-version=2017-12-01&format=json' | \
    jq -r ".compute|to_entries|map(\"\(.key)=\(.value|tostring)\")|.[]" | \
    sed -re 's/^([^=]+)=/AZURE_\U\1 /g' | \
    while read KEY VALUE;
      do echo "${KEY//-/_}=\"${VALUE}\""
    done | tee $tmp

  . $tmp

  if [ -n "$AZURE_TAGS" ]; then
    echo "$AZURE_TAGS" | tr ';' '\n' | sed -r 's/^([^:]+):/AZURE_TAG_\U\1 /g' | while read KEY VALUE; do echo "${KEY//-/_}=\"${VALUE}\""; done | tee -a $tmp
  fi

  curl -fsSL --connect-timeout 1 -H Metadata:true 'http://169.254.169.254/metadata/instance?api-version=2017-12-01&format=json' | \
    jq -r '.network.interface[0].ipv4.ipAddress[0]|[.privateIpAddress,.publicIpAddress]|@tsv' | \
    while read LOCALIP4 PUBLICIPV4; do
        echo "AZURE_LOCALIPV4=${LOCALIP4}"
        test -z "$PUBLICIPV4" || echo "AZURE_PUBLICIPV4=${PUBLICIPV4}"
    done | tee -a $tmp

  . $tmp

  test -z "$AZURE_PUBLICIPV4" || echo "AZURE_DNSLABEL=${AZURE_NAME}.${AZURE_LOCATION}.cloudapp.azure.com"
  )
  local rc=$?
  rm -f $tmp
  return $rc
}

if [ "$(basename -- "$0")" = "$(basename -- ${BASH_SOURCE[0]})" ]; then
  az_metadata_env
fi
