exclude: '^$'
fail_fast: false
repos:
- repo: git://github.com/pre-commit/pre-commit-hooks
  sha: v0.9.1
  hooks:
  - id: trailing-whitespace
  - id: check-yaml
  - id: end-of-file-fixer
  - id: trailing-whitespace
  - id: check-case-conflict
  - id: check-merge-conflict

- repo: git://github.com/pecigonzalo/pre-commit-fmt
  sha: master
  hooks:
  - id: shell-fmt
    args:
      - --indent=4
