version: '3.7'

volumes:
  registry:
  redis:

networks:
  xcalarnet:
    external: true

services:
  redis:
    image: redis:6
    networks:
      - xcalarnet
    volumes:
      - 'redis:/data'
    ports:
      - '6379'

  registry:
    image: registry:2
    container_name: registry
    hostname: registry
    depends_on:
      - redis
    networks:
      - xcalarnet
    volumes:
      - './config.yml:/etc/docker/registry/config.yml:ro'
      - 'registry:/var/lib/registry'
    ports:
      - '5000:5000'
      - '5001:5001'
