AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Xcalar Cluster Serverless Application\nSAM Template for sam-cluster\n
Globals:
  Function:
    Timeout: 300

Resources:
  LibLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: sam-saas-lib
      Description: A set of code shared across functions within sam-saas
      ContentUri: lib/
      CompatibleRuntimes:
        - python3.6
  ClusterFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/cluster
      Handler: cluster.lambda_handler
      Runtime: python3.6
      Layers:
        - !Ref LibLayer
      Events:
        StartCluster:
          Type: Api
          Properties:
            Path: /cluster/start
            Method: post
        StopCluster:
          Type: Api
          Properties:
            Path: /cluster/stop
            Method: post
        GetClusterUrl:
          Type: Api
          Properties:
            Path: /cluster/get
            Method: post

      Policies:
        - Version: '2012-10-17' # Policy Document
          Statement:
            - Effect: Allow
              Action:
                - cloudformation:UpdateStack
                - cloudformation:DescribeStackResource
                - cloudformation:DescribeStacks
                - ec2:DescribeNetworkInterfaces
                - dynamodb:GetItem
                - dynamodb:PutItem
                - dynamodb:UpdateItem
              Resource: '*'
  BillingFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/billing
      Handler: billing.lambda_handler
      Runtime: python3.6
      Layers:
        - !Ref LibLayer
      Events:
        GetCredit:
          Type: Api
          Properties:
            Path: /billing/get
            Method: post
        UpdateCredit:
          Type: Api
          Properties:
            Path: /billing/update
            Method: post
        DeductCredit:
          Type: Api
          Properties:
            Path: /billing/deduct
            Method: post
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:GetItem
                - dynamodb:PutItem
                - dynamodb:Query
              Resource: '*'


Outputs:
  SaaSApi:
    Description: API Gateway endpoint URL for Prod stage for SaaS function
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/v1/'
  ClusterFunction:
    Description: Cluster Lambda Function ARN
    Value: !GetAtt 'ClusterFunction.Arn'
  ClusterFunctionIamRole:
    Description: Implicit IAM Role created for Cluster function
    Value: !GetAtt 'ClusterFunctionRole.Arn'
  BillingFunction:
    Description: Billing Lambda Function ARN
    Value: !GetAtt 'BillingFunction.Arn'
  BillingFunctionIamRole:
    Description: Implicit IAM Role created for Billing function
    Value: !GetAtt 'BillingFunctionRole.Arn'

