#!/bin/bash
exec docker run --detach --init --restart always --name sql_tpch_grafana_datasource --hostname sql_tpch_grafana_datasource -p 3331:80 -v /var/tmp:/var/tmp -v /netstore/qa/jenkins/SqlScaleTest:/netstore/qa/jenkins/SqlScaleTest sql_tpch_grafana_datasource
