xdp-standard-package.zip: applianceCreateUiDefinition.json applianceMainTemplate.json mainTemplate.json
	zip xdp-standard-package.zip applianceCreateUiDefinition.json applianceMainTemplate.json mainTemplate.json

.PHONY: all clean

all: xdp-standard-package.zip

clean:
	rm -f xdp-standard-package.zip
