#!/bin/bash
docker run --detach --init --restart always --name grafana_coverage_datasource --hostname grafana_coverage_datasource -p 3332:80 -v /var/tmp:/var/tmp -v /netstore/qa/coverage:/netstore/qa/coverage grafana_coverage_datasource
