#!/bin/bash
exec docker run --detach --init --restart always --name coverage_grafana_datasource --hostname coverage_grafana_datasource -p 3332:80 -v /var/tmp:/var/tmp -v /netstore/qa/coverage:/netstore/qa/coverage coverage_grafana_datasource
