---
- name: Copy certs
  copy:
    src: "{{ item }}"
    dest: "/etc/xcalar/{{ item }}"
    owner: xcalar
    group: xcalar
  with_items:
    - cert.pem
    - cert.key
  notify: restart caddy
- name: Configure Caddyfile
  lineinfile:
    state: present
    path: /etc/xcalar/Caddyfile
    regexp: '^(\s*)tls .*$'
    line: '\1tls /etc/xcalar/cert.pem /etc/xcalar/cert.key'
    backrefs: yes
  notify: restart caddy
- name: restart-caddy
  become: yes
  become_user: xcalar
  shell: XCE_WORKDIR=/var/tmp/xcalar-root /opt/xcalar/bin/supervisorctl -c /etc/xcalar/supervisor.conf "restart xcalar:caddy"
