#!/bin/bash
exec docker run --detach --init --restart always --name coverage_data_update --hostname coverage_data_update -v /var/tmp:/var/tmp -v /netstore/qa/coverage:/netstore/qa/coverage coverage_data_update
